#include "rack0.hpp"

using namespace rack;

extern Plugin *pluginInstance;

extern Model *modelSupersaw;
extern Model *modelTwinLFO;
extern Model *modelNoise;
extern Model *modelRangeLFO;
extern Model *modelBitCrush;
extern Model *modelWidener;
extern Model *modelFilterDelay;
extern Model *modelSidechain;
extern Model *modelStutter;
extern Model *modelFilter;
extern Model *modelFilters;
extern Model *modelNotch;
extern Model *modelIntegers;
extern Model *modelFloats;
extern Model *modelRandoms;
extern Model *modelLRMixer;
extern Model *modelMono;
extern Model *modelVolumes;
extern Model *modelPanner;
extern Model *modelPanners;
extern Model *modelBPM;
extern Model *modelButton;
extern Model *modelButtons;
extern Model *modelSplitter;
extern Model *modelSplitters;
extern Model *modelDisplays;
extern Model *modelRange;
// extern Model *modelRiser;
extern Model *modelOctaves;
extern Model *modelBPF;
extern Model *modelRandomFilter;
extern Model *modelBuffers;
extern Model *modelChord;
extern Model *modelChordSeq;
extern Model *modelPlayableChord;
// extern Model *modelThreeXOSC;
extern Model *modelGlides;
extern Model *modelMetaKnob;
extern Model *modelReplayKnob;
extern Model *modeluQuant;
extern Model *modelPluck;
extern Model *modelAcid;
extern Model *modelEssEff;
// extern Model *modelDrumpler;
extern Model *modelKTF;
extern Model *modelTriggerSwitch;
extern Model *modelDryWet;
// extern Model *modelPolySidechain;
extern Model *modelMutateSeq;
extern Model *modelNotes;
extern Model *modelSequential;
extern Model *modelSucculent;
// extern Model *modelSoundpipe;
extern Model *modelPingPong;
extern Model *modelBrickwall;
extern Model *modelSlapback;
